apiVersion: v1
kind: Secret
metadata:
  name: langfontfinder
  namespace: wstech
data:
  # This key is for local testing, or development of k8s yaml files 
  # on a test cluster (e.g. minikube etc). Do *not* deploy to production
  # decoded it is: 7f913e60-f9ba-430b-9231-91908fa6c06b
  deploy_key: N2Y5MTNlNjAtZjliYS00MzBiLTkyMzEtOTE5MDhmYTZjMDZi
type: Opaque  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: langfontfinder
  name: langfontfinder
  namespace: wstech
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    nodePort: 30080
  - name: api
    port: 9000
    protocol: TCP
    nodePort: 30900
  selector:
    app: langfontfinder
